### ISSUE TITLE
Grafana dashboards unavailable

### ISSUE THREAD

**Issue by 4n4nd** [operate-first/SRE#109]
For some reason the grafana dashboard resources are not being picked up by the Grafana deployment.

The grafana pod log:
```
t=2021-03-03T16:45:59+0000 lvl=eror msg="Failed to read plugin provisioning files from directory" logger=provisioning.plugins path=/etc/grafana/provisioning/plugins error="open /etc/grafana/provisioning/plugins: no such file or directory"
t=2021-03-03T16:45:59+0000 lvl=eror msg="Can't read alert notification provisioning files from directory" logger=provisioning.notifiers path=/etc/grafana/provisioning/notifiers error="open /etc/grafana/provisioning/notifiers: no such file or directory"
t=2021-03-03T16:45:59+0000 lvl=eror msg="can't read dashboard provisioning files from directory" logger=provisioning.dashboard path=/etc/grafana/provisioning/dashboards error="open /etc/grafana/provisioning/dashboards: no such file or directory"
t=2021-03-03T16:52:00+0000 lvl=eror msg="Failed to look up user based on cookie" logger=context error="user token not found"
t=2021-03-03T16:54:00+0000 lvl=eror msg="Failed to look up user based on cookie" logger=context error="user token not found"
```

**Comment by 4n4nd** [comment]
The issue was that the operator was failing to reconcile because it could not create an ingress for the grafana deployment.

the grafana resource status:
```yaml
status:
  dashboards: null
  failedPlugins: null
  installedPlugins: null
  message: ingress not ready
  phase: failing
  previousServiceName: grafana-service
```
