### ISSUE TITLE
Find out/implement a way for a bot to tag people on a given set of labels within a repo.

### ISSUE THREAD

**Issue by HumairAK** [operate-first/SRE#219]
Due to #215 , we'll be moving all alerts to a single repo. This will make the repo _very_ noisy, so everyone is likely going to mute it to avoid alert fatigue. 

Unfortunately afaik github does not allow you to mute by labels. 

I've noticed that we have some bots that can recognize labels like `lgtm` etc.,  Could we extend this functionality to tag people when a certain label exists within a certain repo? This could then be used to notify people via @mentions.

**Comment by HumairAK** [comment]
@harshad16  @goern

**Comment by HumairAK** [comment]
So for example if I have a config like: 

```yaml
mentions: 
  - repo: operate-first/alerts
    labels: 
      - jupyterhub
      - prometheus
    users:
      - humairak
      - tumido
```

Then the bot would tag `@humairak` and `@tumido` for any issue that has labels `jupyterhub` and `prometheus` in the `operate-first/alerts` repo.
