### ISSUE TITLE
Replace ACM ingress certificate

### ISSUE THREAD

**Issue by larsks** [operate-first/SRE#240]
We would like ACM at https://multicloud-console.apps.moc-infra.massopen.cloud/ to have a signed certificate trusted by major browsers. There are instructions for replacing the certificate [here](https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.2/html/security/security#replacing-the-management-ingress-certificates).

**Comment by larsks** [comment]
Ilana and I are going to run through this manually first to make sure it works. Ideally we would integrate this into the git configuration, but I think this is going to be tricky since it requires editing the `Deployment` resource, and I don't think we want to pull that into our repository.

@tumido @HumairAK do either of you folks have opinions on how to manage this?

**Comment by tumido** [comment]
Why is this not interfaced from the operator, is there any RFE against ACM for it? How is the manual deployment change handled by the operator? Doesn't it reconcile on the managed resource? I think we can patch it from ArgoCD just fine, but if we end up redeploying ACM or upgrading ACM to a version that changes this deployment in the operator, we are risking a race-condition (endless sync loop or failing deployment since we may be doing incompatible changes). I generally don't like a single resource to be managed by 2 different controllers without any coordination.

Off topic:
Is this a pressing issue right now? Do we have to do it right now or is this a task that can be planned for next sprint and worked on as a planned task?

I think we may want to restructure our sprint planning sessions to include @larsks and @ipolonsk to coordinate this better...

WDYT @durandom @HumairAK ?

**Comment by larsks** [comment]
>  Is this a pressing issue right now? Do we have to do it right now or is this a task that can be planned for next sprint and worked on as a planned task?

Figuring out how to manage this properly is absolutely something we can handle in a future sprint. 

We're probably still going to pursue this as time allows right now just to understand what exactly is necessary. It turns out, for example, that the linked documentation is only useful if you're running your own CA, and doesn't work if you're using a "real" ca because it expects you to generate a certificate with a SAN that includes "localhost".

**Comment by larsks** [comment]
@ipolonsk we were SO CLOSE yesterday! The issue with the `reencrypt` route we created yesterday is that we needed to the `destinationCACertificate` key to the tls configuration. This is the CA certificate for the internal CA; we can extract it from the `multicloud-ca-cert` `Secret` in the `acm` namespace:

```
oc get secret multicloud-ca-cert -o json |
  jq -r '.data."tls.crt"' |
  base64 -d
```

This gets us:

```
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: multicloud-console
  namespace: acm
spec:
  host: multicloud-console.apps.moc-infra.massopen.cloud
  port:
    targetPort: https
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: reencrypt
    destinationCACertificate: |
      -----BEGIN CERTIFICATE-----
      MIIFKzCCAxOgAwIBAgIRALhqSEqHUBPzrXMn6lbIAu0wDQYJKoZIhvcNAQELBQAw
      MTEWMBQGA1UEChMNT3BlblNoaWZ0IEFDTTEXMBUGA1UEAxMOd3d3LnJlZGhhdC5j
      b20wHhcNMjEwMjIwMTUyMTU4WhcNMjYwMjE5MTUyMTU4WjAxMRYwFAYDVQQKEw1P
      cGVuU2hpZnQgQUNNMRcwFQYDVQQDEw53d3cucmVkaGF0LmNvbTCCAiIwDQYJKoZI
      hvcNAQEBBQADggIPADCCAgoCggIBANjb8/ViBW2M19PZl9c6U/4gQ6J7zh4WqfS+
      EuOSkG6SundK3xuxAsY7sVjTjII6muC53s0JkhMS0vNYv/YAeL978KOzK2UMsivr
      6vX8SskH5FjcTWkPXYlMMmy6Kah7YwOXC1LznwJRKnZFLwnBaATvpK3Z1++a/YrZ
      sQUZC9hDopEJe26POHj+qzMssfNdtuIRD6BJWLFzF0FfIwVIGjZSCa8yE6dmHOZK
      MLrZcXPVzBAgKt84Iotd8L5pft23N8Z0lel0ZuOLVHsJp+Yw27y8yOI82+ZEqW2u
      zA6L6sUB7PBTNZqxkrUHHfQdcaAFzQMR0C6Xec178VHGlz6iXcKT7U6Ubji+lWKm
      TdGI/jRZaXhcaBuMtHzGKnG6ApCgtD2RSAWai/KsGfQW3kEx9okRajn6JV24sobf
      1azX9q/iC3NqVLrAWXJFgU7uhgw7Pwn+PgZCltHxnK6z7M2NfwSjwA5xx5cWITgn
      QfNZI86p4xBCbPRLx8QVm3F5dxxCrZk9pRZs5oDMu/yugYNiUofG1yTdEQpomSWX
      L2G9o3f6fqgiDLbzAkfwIXzcjZwsZYZ1h6RTmOz9u/3+7a5rcM7k6Rt1xf6H36gp
      qLSyDzLSVAH90mTxG7Byw/UWhxPn0Afy3YvrM9/PHFLBhslBKiBbhhQz3PG+groG
      ETVWs2NLAgMBAAGjPjA8MA4GA1UdDwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/
      MBkGA1UdEQQSMBCCDnd3dy5yZWRoYXQuY29tMA0GCSqGSIb3DQEBCwUAA4ICAQCI
      f0AIVvh5m9uwehvpPYnGQCoYOu15flvlLrXIlM7o8EehvADAFB5D4aaaJDL18NVp
      rx+S2zr7n3pP+f9LYLs+fmZgva+YlC/W615RUzAedNTKdZFGTyy5BR+dK7O6BBxZ
      KxDlW7xPQaryCyYJX/vcCKU1Ndz9x4dy9QOGYY0orxv/Dk7gg+T1a8c6puSaUiP3
      7vqulaTnKF+ikwz2JMZtfusZ0zv49iJDUBnjApApLceYBknSbgh4djrOtkcyM/Uu
      EfUMrc1Rm6DUUhOobRn/xC4FoHnhhKqROKHzqO4+J/NsgolK8e5bPUowLIcZNo3l
      D90Y3k6DyHITtAoYniBpFHmREItZTBIz26r9Ipr7/E6JMq+DJW+9eYBZx8s494nk
      VkpXw0EIwi7MIy/Z0/mWV92n1iYBqVCoYsvnPHONSisB2T16VfO54uyfgUqpo8+J
      MzACOU82NeZxP3LB8+OsalP0W3jrtjglo63L0ooVGAQcfUMLqwW5q7UjFhn2PyVz
      AXkPjNpF1CzABja+vSBQDWC8lmZZD3etClaZD+psZJJKvCwxTV0y+qk66w1WEOt7
      hLj4AL1evUedSOjoYA5HOiokE5TyDmxImw7zSBXZU0Oz1B+nkDKiTuOkU8aO96sX
      wIB+g/oK4tAIE8KhHqFs9t5KIg2PfNdWdzV/YGZe/g==
      -----END CERTIFICATE-----
  to:
    kind: Service
    name: management-ingress
    weight: 100
  wildcardPolicy: None
```

With this in place, ACM uses the default ingress certificate.

Just replacing the route will work until we upgrade ACM, at which
point the route will get replaced. The right way to do this is
apparently via an ACM cluster policy. Gus Parvin suggests:

```
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-acm-route
  annotations:
    policy.open-cluster-management.io/standards: NIST 800-53
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.DS-2 Data-in-transit
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: policy-acm-route-config
      spec:
        remediationAction: inform # will be overridden by remediationAction in parent policy
        severity: low
        namespaceSelector:
          exclude: ["kube-*"]
          include: ["default"]
        object-templates:
          - complianceType: musthave
            objectDefinition:
              apiVersion: route.openshift.io/v1
              kind: Route
              metadata:
                name: multicloud-console
                namespace: open-cluster-management
              spec:
                host: multicloud-console.apps.gparvin.dev08.red-chesterfield.com
                port:
                  targetPort: https
                tls:
                  insecureEdgeTerminationPolicy: Redirect
                  termination: reencrypt
                  destinationCACertificate: |
                    ...internal ca certificate goes here...
                  certificate: |
                    ...custom certificate goes here...
                  key: |
                    ...private key goes here...
                to:
                  kind: Service
                  name: management-ingress
                  weight: 100
                wildcardPolicy: None
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-acm-route
placementRef:
  name: placement-policy-acm-route
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-acm-route
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-acm-route
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: name, operator: In, values: ["local-cluster"]}
```
