### ISSUE TITLE
[MOC Zero] Ceph storage reached its capacity

### ISSUE THREAD

**Issue by tumido** [operate-first/SRE#280]
Edit: Things are starting to hit storage limits due to Ceph capacity.

**Comment by tumido** [comment]
Probably due to full storage https://github.com/operate-first/alerts/issues/5452

**Comment by tumido** [comment]
```
sh-4.4# ceph status
  cluster:
    id:     895c1f68-fc4c-4355-a7bf-51c57c78d59b
    health: HEALTH_WARN
            1 nearfull osd(s)
            10 pool(s) nearfull

  services:
    mon: 3 daemons, quorum e,f,g (age 6d)
    mgr: a(active, since 6d)
    mds: ocs-storagecluster-cephfilesystem:1 {0=ocs-storagecluster-cephfilesystem-b=up:active} 1 up:standby-replay
    osd: 9 osds: 9 up (since 6d), 9 in (since 6d)
    rgw: 2 daemons active (ocs.storagecluster.cephobjectstore.a, ocs.storagecluster.cephobjectstore.b)

  task status:
    scrub status:
        mds.ocs-storagecluster-cephfilesystem-a: idle
        mds.ocs-storagecluster-cephfilesystem-b: idle

  data:
    pools:   10 pools, 464 pgs
    objects: 1.22M objects, 1.1 TiB
    usage:   3.4 TiB used, 1.5 TiB / 4.9 TiB avail
    pgs:     464 active+clean

  io:
    client:   13 MiB/s rd, 24 MiB/s wr, 54 op/s rd, 3.16k op/s wr
```
