### ISSUE TITLE
Ceph cluster in warning state

### ISSUE THREAD

**Issue by larsks** [operate-first/SRE#322]
See https://github.com/operate-first/alerts/issues/7787

Ceph cluster reports one mon out of quorum:

```
sh-4.4# ceph -s
  cluster:
    id:     895c1f68-fc4c-4355-a7bf-51c57c78d59b
    health: HEALTH_WARN
            1 slow ops, oldest one blocked for 261342 sec, mon.f has slow ops
            1/3 mons down, quorum f,g

  services:
    mon: 3 daemons, quorum f,g (age 3d), out of quorum: e
    mgr: a(active, since 3d)
    mds: ocs-storagecluster-cephfilesystem:1 {0=ocs-storagecluster-cephfilesystem-b=up:active} 1 up:standby-replay
    osd: 9 osds: 9 up (since 3d), 9 in (since 4w)
    rgw: 2 daemons active (ocs.storagecluster.cephobjectstore.a, ocs.storagecluster.cephobjectstore.b)

  task status:
    scrub status:
        mds.ocs-storagecluster-cephfilesystem-a: idle
        mds.ocs-storagecluster-cephfilesystem-b: idle

  data:
    pools:   10 pools, 464 pgs
    objects: 1.33M objects, 798 GiB
    usage:   2.5 TiB used, 2.4 TiB / 4.9 TiB avail
    pgs:     464 active+clean

  io:
    client:   30 MiB/s rd, 42 MiB/s wr, 316 op/s rd, 59 op/s wr
```

...and also that message about "1 slow ops". We need to figure out what's up with the one monitor, because if another fails the service will become unavailable.
