### ISSUE TITLE
A question about existing clusterrolebindings

### ISSUE THREAD

**Issue by larsks** [operate-first/SRE#368]
We create a clusterolebinding named `cluster-admins-rb` to grant cluster admin privileges to the `cluster-admins` group.

OpenShift ships with two existing clusterrolebindings named `cluster-admin`:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:masters
```

And `cluster-admins`:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: cluster-admins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:cluster-admins
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:admin
```

I'm not sure what the principals `system:cluster-admins` or
`system:masters` refer to. Can we utilize these bindings instead of
creating our own? Does anyone know what they're for?

Thanks!
