### ISSUE TITLE
If we stop using KSOPS, how do we handle non-Secret secret data?

### ISSUE THREAD

**Issue by larsks** [operate-first/SRE#384]
This came up on the call this morning:

If the work in https://github.com/orgs/operate-first/projects/18 results in us adopting a solution other than KSOPS for managing secret data in our repositories, how will we handle secret data that is not actually a `Secret` resource (for example, right now we also encrypt `Groups` and some custom resources that embed secrets, such as KeyCloak client definitions)? Most solutions (external secrets, sealed secrets, etc) only operate on `Secret` resources.

One solution that we discussed would be a custom control that reads data from a `Secret` and inflates that into another resource type. For example, if we wanted to create a `cluster-admins` group but we did not want to store the group directly in the repository, we might create a `Secret` like this (stored in Vault, or via sealed secret, etc):

```
apiVersion: v1
kind: Secret
metadata:
  name: cluster-admins-group
  labels:
    operatefirst.cloud/secret-manifest: ""

stringData:
  manifest: |
    apiVersion: user.openshift.io/v1
    kind: Group
    metadata:
      labels:
        app.kubernetes.io/instance: cluster-resources-infra
      name: cluster-admins
    users:
      - alice@example.com
      - bob@example.com
```

Our controller would look for secrets with the label `operatefirst.cloud/secret-manifest`, and perform the equivalent of passing the contents of the `manifest` key to `kubectl apply`.
