### ISSUE TITLE
How much space to allocate for object storage?

### ISSUE THREAD

**Issue by larsks** [operate-first/SRE#405]
It looks like Noobaa (the object storage service) by default creates a 50GB PV for holding bucket data. This sounds small to me, but I don't know how much data we're expecting to generate. The default backingstore manifest looks like this:

```
apiVersion: noobaa.io/v1alpha1
kind: BackingStore
metadata:
  labels:
    app: noobaa
  name: noobaa-default-backing-store
  namespace: openshift-storage
spec:
  pvPool:
    numVolumes: 1
    resources:
      requests:
        storage: 50Gi
  type: pv-pool
```
It's not clear to me if we change the storage setting by:

- Changing `spec.pvPool.resources.requests.storage`
- Changing `spec.pvPool.numVolumes`
- Creating additional backingstore resources

I'm going to ask around the OCS google chat to see if someone has an answer.
