### ISSUE TITLE
Should we be using impersonation rather than cluster-admin role?

### ISSUE THREAD

**Issue by larsks** [operate-first/SRE#429]
We currently assign the cluster-admin role directly to user accounts. This means we have some of the same risks as someone who always runs commands on their local system as `root`: it increases the blast radius for what would otherwise be an innocent typo (e.g., running something like `oc delete pod --all` in the wrong namespace).

Should we be using [impersonation](https://docs.openshift.com/container-platform/4.9/authentication/impersonating-system-admin.html) instead? This allows us to grant admin access to people but in a way that it has to be requested explicitly.

Using impersonation, our regular accounts would be unprivileged (we might have access to specific projects, but we wouldn't have cluster-admin access). When we need to run commands as a cluster admin, we would use the `--as` option to `oc`, as in:

```
oc --as system:admin get pod -A
```

**Comment by HumairAK** [comment]
omg this is great, we should do this!

**Comment by HumairAK** [comment]
Question: How does this affect console access? Will we have to perform all cluster-admin-y actions via cli, if we do this?

**Comment by larsks** [comment]
The console *does* support user impersonation (go to https://console-openshift-console.apps.smaug.na.operate-first.cloud/k8s/cluster/user.openshift.io~v1~User, click the "⋮" menu to the right of a user, and select "Impersonate User ..."), but this only seems to work with actual `User` objects.

**Comment by HumairAK** [comment]
Eh, I think it's a minor inconvenience for the gains, just bookmark the path to a cluster-admin account. WDYT?

**Comment by larsks** [comment]
I am totally in favor of trying this out.

**Comment by dystewart** [comment]
@HumairAK What cluster(s) should I test this out in first?

**Comment by HumairAK** [comment]
@dystewart what do you mean by testing it out? If you'd like to try out the command, you can do it in a dev cluster, or add yourself to the sudo'ers list in morty cluster as @rbo suggests. Feel free to go ahead and add the rolebindings for the other clusters like in: https://github.com/operate-first/apps/pull/1725

Remove all cluster admins in all clusters, but make sure they are added to the `sudoers` group for each cluster.

**Comment by dystewart** [comment]
Added myself as a sudoer in the morty cluster [https://github.com/operate-first/apps/pull/1803](https://github.com/operate-first/apps/pull/1803)

**Comment by HumairAK** [comment]
@dystewart were you able to access the console with your implementation here: https://github.com/operate-first/apps/pull/1855 
as cluster admin? If not do we need to create a cluster admin user that the sudoers can impersonate to do this?

**Comment by dystewart** [comment]
Referencing [#1855](https://github.com/operate-first/apps/pull/1855)
@HumairAK as I am added to the sudoers group in the Morty cluster if I run:
```
$ oc whoami
dystewart
```
If I use the whoami command and specify system admin however:
```
$ oc whoami --as system:admin
system:admin
```

The impersonation is taken care of using the impersonate verb in the sudoer clusterrole:
```
kind: clusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sudoer
rules:
  - verbs:
      - impersonate
    apiGroups:
      - ''
      - user.openshift.io
    resources:
      - systemusers
      - users
    resourceNames:
      - 'system:admin'
  - verbs:
      - impersonate
    apiGroups:
      - ''
      - user.openshift.io
    resources:
      - groups
      - systemgroups
    resourceNames:
      - 'system:masters'
```

We are just impersonating the built in system admin user so we wont need to create a separate cluster admin to impersonate.

**Comment by HumairAK** [comment]
@dystewart You are still using the cli. I'm referring to the openshift-console web ui (example [here](https://console-openshift-console.apps.smaug.na.operate-first.cloud)). If we remove everyone from cluster-admins as done so in the PR,  is there a way for us to still use the console as a cluster-admin? Is there an `--as system:admin` equivalent for the ui?

**Comment by dystewart** [comment]
@HumairAK impersonation via the console is available for users and groups however the only way to impersonate a group that I am seeing is through the `clusterrolebinding` options. It looks like there used to be an option to impersonate a group via the group options, see [https://cloud.redhat.com/blog/openshift-4-3-spoofing-a-user](https://cloud.redhat.com/blog/openshift-4-3-spoofing-a-user) 

Unfortunately, there doesn't appear to be a way to impersonate the default system:admin user provided by the sudoer `clusterrole`, but I will create a separate admin user in Morty which sudoers can impersonate and see if this works

**Comment by dystewart** [comment]
@HumairAK Actually scratch that you can impersonate the system:admin subject from the console, I was just trying to impersonate through the wrong clusterrolebinding. 

```
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: 'system:cluster-admins'
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: 'system:admin'   <---------------- Here is the subject that makes it work
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
```

So the sudoer role will suffice the needs of cluster admins without having users in the cluster-admins group.
