### ISSUE TITLE
IAM User required for adding cert manager to manage secrets on MOC Infra cluster

### ISSUE THREAD

**Issue by HumairAK** [operate-first/SRE#433]
We need an Iam user account to feed to cert manager so that we can have it manage the certs for infra cluster.

Related: https://github.com/operate-first/apps/issues/1415\

We need: 

- dnsZone
- hostedZoneID
- access key id
- Secret access key

**Comment by larsks** [comment]
Other information can be found in https://github.com/CCI-MOC/moc-apps/blob/master/cluster-scope/base/cert-manager.io/clusterissuers/letsencrypt-production-http.yaml and https://github.com/CCI-MOC/moc-apps/blob/master/cluster-scope/overlays/ocp-prod/certificates/default-ingress-certificate.yaml.

**Comment by larsks** [comment]
Here's the ClusterIssuer from the ocp-prod cluster:

```
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production-dns01
spec:
  acme:
    email: ...
    preferredChain: ""
    privateKeySecretRef:
      name: letsencrypt-production-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cnameStrategy: Follow
        route53:
          accessKeyID: ...
          hostedZoneID: Z04486682XFINHTESP6B9
          region: us-east-1
          secretAccessKeySecretRef:
            key: aws_secret_access_key
            name: aws-route53-secret
      selector:
        dnsZones:
        - ocp-prod.massopen.cloud
```

You'll need to replace the zone in the `selector` with
`moc-infra.massopen.cloud`.
